services:
  # Backend (Node.js API)
  - type: web
    name: foodzilla-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd backend && npm ci
    startCommand: cd backend && node server.js
    envVars:
      PORT: "10000"
      MONGO_URI: mongodb+srv://abhishekroyal630396_db_user:ZLj7OQVI6m9LL9Sf@cluster0.e3bbbls.mongodb.net/foodzilla_real_db?retryWrites=true&w=majority

  # Frontend (React â€“ Static Site)
  - type: web
    name: foodzilla-frontend
    env: static
    plan: free
    region: oregon
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html